name: Build dnSpy win-x64

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    name: Build win-x64
    runs-on: windows-latest

    defaults:
      run:
        shell: pwsh

    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2
        with:
          submodules: true

      - name: Setup .NET
        uses: actions/setup-dotnet@v5.2.0
        with:
          dotnet-version: 10.0.x
          dotnet-quality: ga

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2.0.0

      - name: Build dnSpy (net-x64)
        run: .\build.ps1 net-x64

      - name: Create output directory
        run: New-Item -ItemType Directory -Path C:\builtfiles\dnSpy-net-win64 -Force > $null
        continue-on-error: true

      - name: Copy release files for upload
        run: Copy-Item -Path dnSpy\dnSpy\bin\Release\net10.0-windows\win-x64\publish\* -Destination C:\builtfiles\dnSpy-net-win64 -Recurse

      - name: Upload artifact
        uses: actions/upload-artifact@v7.0.0
        with:
          name: dnSpy-net-win64
          path: C:\builtfiles\dnSpy-net-win64
          if-no-files-found: error
          compression-level: 9
